#!/bin/bash
sudo apt-get install cmake gcc qtbase5-dev qtdeclarative5-dev qml-module-qtquick2 qml-module-qtquick-controls2
git clone https://github.com/cutefishos/calculator.git
mkdir ~/calculator/build
cd ~/calculator/build
cmake ..
make
sudo make install
